---
jenkins_plugins:
    - ant
    - antisamy-markup-formatter
    - credentials
    - cvs
    - external-monitor-job
    - javadoc
    - junit
    - ldap
    - mailer
    - matrix-auth
    - matrix-project
    - maven-plugin
    - pam-auth
    - script-security
    - ssh-credentials
    - ssh-slaves
    - subversion
    - translation
    - windows-slaves


