---
- name: Prepare basic env for php apps on all nodes
  hosts: 127.0.0.1
  connection: local
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars_files:
    - variables.yml
  roles:
    - tools
    - jenkins
    - docker
