---
- name: Add brackets.io repository
  apt_repository: repo='ppa:webupd8team/brackets'

- name: Update apt
  apt: update_cache=yes

- name: Install regular tools
  apt: name={{ item }} state=latest
  with_items:
    - python-pip
    - git-core
    - curl
    - mc
    - acl
    - htop
    - zip
    - lxde
    - brackets
    - firefox
