---
- name: Add apt key to docker
  shell: "sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"

- name: Add repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present

- name: Update repository
  apt: update_cache=yes

- name: Install docker
  apt: name=docker-engine

- name: Add vagrant user to docker group
  shell: usermod -aG docker vagrant
  become: yes

- name: Install docker-compose
  shell: 'pip install docker-compose'
  become: yes
